name: Mica

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t imadwrgh/mica:latest .

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Push Docker image
        run: docker push imadwrgh/mica:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Server and Pull Docker Image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 156.67.81.207
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/tp1/imad_ASSERNE
            docker pull imadwrgh/mica:latest
            if [ $(docker ps -a -q -f name=container-imad) ]; then
              docker stop container-imad
              docker rm container-imad
            fi
            docker run -d --name container-imad -p 4545:4545 -v /home/tp1/imad_ASSERNE:/app imadwrgh/mica:latest